name: Image

on: [push, pull_request]

jobs:
  armv64_job:
    name: Build image for arm64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx
        uses: docker/setup-Buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: priyaa221
          password: $Anuj221$
      - name: Build and Publish API
        uses: docker/build-push-action@v2
        with:
         context: ./crystal_grpc_bench
         file: ./crystal_grpc_bench/Dockerfile
         platforms: linux/arm64,linux/amd64
         push: true
         tags: priyaa221/crystal_grpc_bench:latest_arm
